services:
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.debug
    entrypoint: /entrypoint.sh
    command: >
      sh -c "python -m debugpy --wait-for-client --listen 0.0.0.0:5678 
      manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    networks:
      - backend
    ports:
      - 8000:8000
      - 5678:5678
    expose:
      - 8000
      - 5678
    env_file:
      - ./.env
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
  db:
    image: postgres:17-bullseye
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend
volumes:
  static_volume: {}
  db: {}

networks:
  backend:
    driver: bridge